CREATE USER SERVIDOR_TEST_ok IDENTIFIED BY servidor123;
CREATE USER SERVIDOR_TEST_be IDENTIFIED BY servidor123;
CREATE USER SERVIDOR_TEST_tb IDENTIFIED BY servidor123;

GRANT CONNECT, RESOURCE, DBA TO SERVIDOR_TEST_ok;
GRANT CONNECT, RESOURCE, DBA TO SERVIDOR_TEST_be;
GRANT CONNECT, RESOURCE, DBA TO SERVIDOR_TEST_tb;